Total Refactor from Head to Toe
PolicyStat/ckeditor-plugin-structured-headings pull request #17
Opened 2016-12-14 20:30 UTC by BDeveau

# WHAT IS? 
For issue #15 

Total Refactor of entire plugin code

2016-12-14 21:54 UTC, caffodian requested changes
Diff is crazy but doesn't seem too bad.  So glad we have tests on the plugin that give more confidence we did right.

See the comment about IIFE though - I'm pretty sure this will be the case...  pretty minor change though.

2016-12-14 21:54 UTC, caffodian commented on structuredheadings/plugin.js
> +var allowedElements = {
Because this isn't a proper, I think you will need to wrap the entire file into an IIFE .  Otherwise I think these all just get shoved onto window

2016-12-14 21:54 UTC, caffodian commented on structuredheadings/plugin.js
> +for (var key in allowedElements) {headerList.push(key);}
ordering not guaranteed?

2016-12-15 14:44 UTC, BDeveau commented
True on both counts... code wrapped in a function and I reverted back to hard coding the array of headers.

2016-12-15 15:16 UTC, caffodian approved these changes

2016-12-15 19:15 UTC, merged