Allow customizing element list (can start from H2)
PolicyStat/ckeditor-plugin-structured-headings pull request #28
Opened 2017-01-20 18:52 UTC by BDeveau

## What It is
- List of numbered elements is now configurable
- Element numbering is based on it's position in the list (number does not start from h1, it starts from element 0)
- CSS updated with new classes to signify position in numbering list (autonumber-0, autonumber-1)

2017-01-20 21:33 UTC, caffodian commented on structuredheadings/styles/numbering.css
> +.autonumber.autonumber-5 {
ah I was curious how you addressed this

I think we should rename the counter names as well since they're still named after the heading tags

2017-01-20 21:35 UTC, BDeveau commented on structuredheadings/styles/numbering.css
> +.autonumber.autonumber-5 {
Eh I suppose, I just thought of it as "heading level 1, heading level 2" and left em, but I can change them no prob.

2017-01-20 21:35 UTC, caffodian requested changes
looks good  we should add a test where we actually skip h1 as intended, and enable a heading.

I think we need more test coverage for this config.  

also, skip h1, be in an h2, check that the previous button greys out properly.  Same for the other end of the boundary as well.

We should also check the behaviour of the command when a heading is excluded, and the cursor is inside one of the prohibited headings

2017-01-20 21:35 UTC, caffodian commented on structuredheadings/styles/numbering.css
> +.autonumber.autonumber-5 {
also, for better mental mapping to the default set (1-6) perhaps these classes should be 1-6 as well?

2017-01-20 21:38 UTC, BDeveau commented on structuredheadings/styles/numbering.css
> +.autonumber.autonumber-5 {
Depends on where your mind is at, I've been in the mindset of "array index" which is what those classes indicate, so if I change the class to be 1-6, I'll need to adjust the code to be index + 1 :)

2017-01-20 21:40 UTC, caffodian commented on structuredheadings/styles/numbering.css
> +.autonumber.autonumber-5 {
Hmmm yea having index+1 in the code is probably worse.  Should still change the counter names I think to match the classes

2017-01-23 21:53 UTC, caffodian approved these changes
test updates look good!

2017-01-23 23:17 UTC, merged